#!/bin/bash

index="index.html"

model="index_model.html"
pattern="<!-- App scripts -->"

shopt -s nullglob
shopt -s globstar

function scrivi () {
	sed "/${pattern}/q" <"${model}"

	m="static/main.js"
	echo "    <script src=\"${m}\"></script>"

	for i in static/**/*.js
	do
		[[ ${i} == ${m} ]] ||
		echo "    <script src=\"${i}\"></script>"
	done
	sed "0,/${pattern}/d" <"${model}"
} >"${index}"


[[ $1 =~ -i ]] &&
inotifywait -m -r -e move,create,delete --format '%f' "static/" | while read file_name
do
	[[ ${file_name} =~ .*js ]] && scrivi >"${index}"
done

[[ $1 =~ -s ]] && scrivi

