services:
  ricette_personali_bot:
    image: telegram_bot:arm
    volumes:
      - persistence:/var/local/persistence
      - ${CATALOGO_PATH}:/var/local/database:ro
    environment:
      - TOKEN
  sito_ricette:
    image: web_ui:arm
    volumes:
      - ${CATALOGO_PATH}:/var/local/database
      - ${WWW_PATH}:/var/www
    ports:
      - "80:80"

volumes:
  persistence:
