version: "3.8"
services:
  ricette_personali_bot:
    image: telegram_bot:arm
    volumes:
      - persistence:/var/local/persistence
      - ${CATALOGO_PATH}:/var/local/database:ro
    environment:
      - TOKEN
  sito_ricette:
    image: web_ui:arm
    volumes:
      - ${CATALOGO_PATH}:/var/local/database
      - ${WWW_PATH}:/var/www
    ports:
      - 8:80
  backup:
    image: backup_catalogo:arm
    volumes:
      - ${CATALOGO_PATH}:/var/local/database

volumes:
  persistence:
